version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[gh-actions]"
      include: scope
    labels:
      - internal
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
