version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/dandi-publish
    ports:
      - 8000:8000
    depends_on:
      # TODO: https://docs.docker.com/compose/startup-order/
      - db
      - rabbitmq
      - minio

  worker:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: ["celery", "worker", "--app", "dandi.celery", "--loglevel", "info", "--without-heartbeat"]
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/dandi-publish
    depends_on:
      - db
      - rabbitmq
      - minio
