version: 2
jobs:
  test-server:
    docker:
      - image: circleci/python:3.6
      - image: circleci/mongo:4.2
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/data/db"]
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install -U pip
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tests
          command: tox
          working_directory: girder-dandi-archive

  test-gui:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install web app dependencies
          command: yarn install --frozen-lockfile
          working_directory: web
      - run:
          name: Lint web app
          command: yarn run lint
          working_directory: web
      - run:
          name: Build web app
          command: yarn run build
          working_directory: web

  test-end-to-end:
    docker:
      - image: circleci/python:3.6-node-browsers
      - image: circleci/mongo:4.2
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/data/db"]
    steps:
      - checkout
      - run:
          name: Create a virtualenv for installation
          command: |
            python3 -m venv install_env
            . install_env/bin/activate
      - run:
          name: Upgrade pip
          command: pip install -U pip
      - run:
          name: Install girder-dandi-archive
          command: |
            whereis python
            whereis pip
            pip install .
          working_directory: girder-dandi-archive
      - run:
          name: Run girder-dandi-archive in the background
          command: girder serve
          working_directory: girder-dandi-archive
          background: true
      - run:
          name: Install web app
          command: yarn install --frozen-lockfile
          working_directory: web
      - run:
          name: Run web app
          command: yarn serve
          working_directory: web
          background: true
      - run:
          name: Install tests
          command: yarn install --frozen-lockfile
          working_directory: test
      - run:
          name: Run tests
          command: yarn run test
          working_directory: test
          environment:
            CLIENT_URL: http://localhost:8085

  provision:
    docker:
      - image: circleci/python:3.6
    environment:
      ANSIBLE_PRIVATE_KEY_FILE: "$HOME/girder-dandi-server.pem"
    steps:
      - checkout
      - run:
          name: Create a virtualenv for deployment
          command: |
            python3 -m venv deployment_env
            . deployment_env/bin/activate
      - run:
          name: Activate virtual environment
          command: echo ". $CIRCLE_WORKING_DIRECTORY/deployment_env/bin/activate" >> $BASH_ENV
      - run:
          name: Upgrade pip
          command: pip install -U pip
      - run:
          name: Install ansible
          command: pip install ansible
      - run:
          name: Echo key to a file
          command: echo -e "$DEPLOYKEY" > "$HOME/girder-dandi-server.pem"
      - run:
          name: Change key permission
          command: chmod 600 "$HOME/girder-dandi-server.pem"
      - run:
          name: Run ansible playbook
          working_directory: ./ansible
          command: . ./provision.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test-server
      - test-gui
      - test-end-to-end:
          requires:
            - test-server
            - test-gui
      - provision:
          requires:
            - test-end-to-end
          filters:
            branches:
              only: refactor
