---
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:12-alpine-ram
      - image: minio/minio
        command: server /data
        environment:
          MINIO_ACCESS_KEY: djangoAccessKey
          MINIO_SECRET_KEY: djangoSecretKey
    steps:
      - checkout
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run tests
          command: tox
          environment:
            DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/dandi
            DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
            DJANGO_MINIO_STORAGE_ACCESS_KEY: djangoAccessKey
            DJANGO_MINIO_STORAGE_SECRET_KEY: djangoSecretKey

workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
