# Generated by Django 4.1.13 on 2024-08-30 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usermetadata_webknossos_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebKnossosDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webknossos_dataset_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('webknossos_dataset_name', models.CharField(max_length=100)),
                ('webknossos_organization_name', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webknossos_datasets', to='api.asset')),
            ],
        ),
        migrations.CreateModel(
            name='WebKnossosAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webknossos_annotation_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('webknossos_annotation_name', models.CharField(max_length=100)),
                ('webknossos_organization', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webknossos_annotations', to='api.asset')),
                ('webknossos_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_annotations', to='api.webknossosdataset')),
            ],
        ),
    ]
