# Generated by Django 4.1.13 on 2024-09-03 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usermetadata_webknossos_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebKnossosDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webknossos_dataset_name', models.CharField(blank=True, max_length=100, null=True)),
                ('webknossos_organization_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebKnossosDataLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_datasets', to='api.asset')),
                ('webknossos_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_datalayers', to='api.webknossosdataset')),
            ],
        ),
        migrations.CreateModel(
            name='WebKnossosAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webknossos_annotation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('webknossos_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('webknossos_annotation_owner_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('webknossos_annotation_owner_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_annotations', to='api.asset')),
                ('webknossos_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_annotations', to='api.webknossosdataset')),
            ],
        ),
    ]
