# Generated by Django 4.1.13 on 2024-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_webknossosdataset_webknossosdatalayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webknossosannotation',
            name='webknossos_annotation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
