# Generated by Django 4.1.13 on 2024-09-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_webknossosdataset_webknossosannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='webknossosannotation',
            name='webknossos_annotation_owner_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webknossosannotation',
            name='webknossos_annotation_owner_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webknossosannotation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_annotations', to='api.asset'),
        ),
        migrations.AlterField(
            model_name='webknossosannotation',
            name='webknossos_annotation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webknossosannotation',
            name='webknossos_organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webknossosdataset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webknossos_datasets', to='api.asset'),
        ),
        migrations.AlterField(
            model_name='webknossosdataset',
            name='webknossos_dataset_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webknossosdataset',
            name='webknossos_organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
