# Generated by Django 4.1.13 on 2024-09-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_webknossosannotation_webknossos_annotation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webknossosannotation',
            name='asset',
        ),
    ]
