# Generated by Django 4.2.20 on 2025-04-10 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auditrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DandisetStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarbageCollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(help_text='The model name of the records that were garbage collected.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GarbageCollectionEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.JSONField(help_text='JSON serialization of the record that was garbage collected.')),
            ],
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assetpath',
            name='path',
            field=models.CharField(db_collation='C', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='auditrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin', False), ('description', '')), models.Q(('admin', True), models.Q(('description', ''), _negated=True)), _connector='OR'), name='admin-description-pairing'),
        ),
        migrations.AddField(
            model_name='garbagecollectioneventrecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.garbagecollectionevent'),
        ),
        migrations.AddField(
            model_name='dandisetstar',
            name='dandiset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='api.dandiset'),
        ),
        migrations.AddField(
            model_name='dandisetstar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dandiset_stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dandiset',
            name='starred_users',
            field=models.ManyToManyField(related_name='starred_dandisets', through='api.DandisetStar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dandisetstar',
            constraint=models.UniqueConstraint(fields=('user', 'dandiset'), name='unique-user-dandiset-star'),
        ),
    ]
