version: '3'
services:

  mongo:
    image: mongo:latest
    volumes:
      - dandi_girder_mongo_db:/data/db

  girder:
    build:
      context: ../
      dockerfile: docker/girder.Dockerfile
    image: dandi_girder
    volumes:
      - dandi_girder_assetstore:/home/assetstore
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  client:
    build:
      context: ../
      dockerfile: docker/client.Dockerfile
    image: dandi_client
    depends_on:
      - girder
    ports:
      - "8085:80"

  provision:
    build:
      context: ../
      dockerfile: docker/provision.Dockerfile
    image: dandi_provision
    depends_on:
      - client

volumes:
  dandi_girder_mongo_db:
  dandi_girder_assetstore:
