---
- name: Deploy https://girder.dandiarchive.org/
  hosts: all
  vars:
    ansible_python_interpreter: auto

  roles:
    - role: girder.mongodb
      vars:
        mongodb_data_path: /var/lib/mongodb
    - role: girder.girder
    - role: girder.nginx
      vars:
        nginx_hostname: "girder.dandiarchive.org"
        nginx_registration_email: "michael.grauer@kitware.com"

  tasks:
    - name: Install awscli
      apt:
        name: awscli
        update_cache: true
      become: true

    - name: Install mongo-tools
      apt:
        name: mongodb-org-tools
      become: true

    - name: Create backups directory
      file:
        path: "{{ ansible_env.HOME }}/backups"
        state: directory

    - name: Create .aws directory
      file:
        path: "{{ ansible_env.HOME }}/.aws"
        state: directory

    - name: Copy aws config file required for public S3 bucket in separate aws account
      copy:
        src: files/config
        dest: "{{ ansible_env.HOME }}/.aws/config"

    - name: Install Girder plugins
      pip:
        name:
          - "git+https://github.com/dandi/dandiarchive@{{ lookup('env', 'CIRCLE_SHA1') }}#subdirectory=girder-dandi-archive"
        virtualenv: "{{ girder_virtualenv }}"
        state: latest

    - name: Make sure handlers are called
      command: /bin/true
      notify:
        - Build Girder web client
        - Restart Girder

  post_tasks:
    - name: Copy backup-mongo script
      copy:
        src: backup-mongo
        dest: /usr/local/bin
        mode: 0775
      become: true
      become_user: root

    - name: Install backup-mongo cron job
      cron:
        name: mongodump
        job: "/usr/local/bin/backup-mongo"
        special_time: daily
      become: true
      become_user: root

