name: Trigger staging deploy of backend server on push to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - "web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install builds plugin
        run: heroku plugins:install heroku-builds

      - name: Build app into tarball
        run: |
          git fetch --prune --unshallow --tags
          python setup.py sdist --formats=gztar

      - name: Create Heroku Build
        run: heroku builds:create -a dandi-api-staging --source-tar=dist/$(python setup.py --fullname).tar.gz
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY  }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL  }}
