name: Test Integration with dandi-cli

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.7
          - 3.8
          - 3.9
        dandi-version:
          - release
          - master
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            -t dandiarchive/dandiarchive-api \
            -f dev/django.Dockerfile \
            .

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install hdf5
        if: matrix.python == '3.9'
        run: sudo apt-get update && sudo apt-get install -y libhdf5-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # As of 2021-02-01, the latest version of hdmf (v2.3.0) requires
          # numpy >=1.16, <1.19.4, so we end up with numpy 1.19.3 installed.
          # However, due to the release of numpy 1.20.0 on January 30, h5py
          # gets built against the later version instead, and because numpy
          # 1.20.0 changed the size of ndarray, an error results at runtime.
          # This can be worked around by installing numpy before the other
          # dependencies so that it is available when h5py is built.
          pip install 'numpy<1.19.4'

      - name: Install released dandi
        if: matrix.dandi-version == 'release'
        run: pip install "dandi[test]"

      - name: Install dev dandi
        if: matrix.dandi-version == 'master'
        run: pip install "dandi[test] @ git+https://github.com/dandi/dandi-cli"

      - name: Run dandi-api tests in dandi-cli
        run: |
          python -m pytest -s -v --dandi-api \
            "$pythonLocation/lib/python${{ matrix.python }}/site-packages/dandi"
        working-directory: /tmp
