name: Backup Heroku Database to S3

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Heroku Login
        run: |
          heroku auth:token -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Capture Backup
        run: |
          PGPASSWORD=$(heroku config:get DATABASE_PASSWORD -a ${{ secrets.HEROKU_APP_NAME }}) pg_dump -Fc --no-acl --no-owner -h $(heroku config:get DATABASE_HOST -a ${{ secrets.HEROKU_APP_NAME }}) -U $(heroku config:get DATABASE_USER -a ${{ secrets.HEROKU_APP_NAME }}) $(heroku config:get DATABASE_NAME -a ${{ secrets.HEROKU_APP_NAME }}) > db.dump

      - name: Upload Backup to S3
        run: |
          aws s3 cp db.dump s3://${{ secrets.S3_BUCKET_NAME }}/$(date +%Y-%m-%d_%H-%M-%S)_db.dump
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
