name: Update release branch

on:
  release:
    types: [released]

jobs:
  reset-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch history for all branches and tags
          token: ${{ secrets.GH_TOKEN }} # use PAT with permissions to push to master
          ref: release

      - name: Perform reset
        run: |
          git reset --hard ${{ github.ref }}
          git push --force origin release

  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch history for all branches and tags
          token: ${{ secrets.GH_TOKEN }} # use PAT with permissions to push to master
          ref: release

      - name: Get latest git tag
        run: |
          git fetch --prune --unshallow
          echo "API_VERSION=$(git describe --abbrev=0)" >> $GITHUB_ENV

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dandi-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_DJANGO_DANDI_API_VERSION: ${{ env.API_VERSION }}
