[build]
publish = "dist"
command = "git fetch --tags && yarn run build"
ignore = "false"

# Staging
[context.staging.environment]
NODE_VERSION = "20" # Netlify defaults to node.js 10, but @types/node requires a more recent version
VITE_APP_OAUTH_API_ROOT = "https://staging-api.lincbrain.org/oauth/"
VITE_APP_OAUTH_CLIENT_ID = "Dk0zosgt1GAAKfN8LT4STJmLJXwMDPbYWYzfNtAl"
VITE_APP_DANDI_API_ROOT = "https://staging-api.lincbrain.org/api/"
VITE_APP_SENTRY_DSN = "https://833c159dc622528b21b4ce4adef6dbf8@o4506237212033024.ingest.sentry.io/4506237213212672"
VITE_APP_SENTRY_ENVIRONMENT = "staging"
VITE_CLOUDFRONT_NEUROGLANCER_URL = "https://neuroglancer-staging.lincbrain.org"
VITE_APP_WEBKNOSSOS_API_ROOT="https://webknossos-staging.lincbrain.org/"

# Deploy previews
[context.deploy-preview.environment]
NODE_VERSION = "20" # Netlify defaults to node.js 10, but @types/node requires a more recent version
VITE_APP_OAUTH_API_ROOT = "https://staging-api.lincbrain.org/oauth/"
VITE_APP_OAUTH_CLIENT_ID = "Dk0zosgt1GAAKfN8LT4STJmLJXwMDPbYWYzfNtAl"
VITE_APP_DANDI_API_ROOT = "https://staging-api.lincbrain.org/api/"
VITE_APP_SENTRY_DSN = "https://833c159dc622528b21b4ce4adef6dbf8@o4506237212033024.ingest.sentry.io/4506237213212672"
VITE_APP_SENTRY_ENVIRONMENT = "staging"
VITE_CLOUDFRONT_NEUROGLANCER_URL = "https://neuroglancer-staging.lincbrain.org/"
VITE_APP_WEBKNOSSOS_API_ROOT="https://webknossos-staging.lincbrain.org/"

# Production
[context.release.environment]
NODE_VERSION = "20" # Netlify defaults to node.js 10, but @types/node requires a more recent version
VITE_APP_OAUTH_API_ROOT = "https://api.lincbrain.org/oauth/"
VITE_APP_OAUTH_CLIENT_ID = "29651e4821c59cba741b"
VITE_APP_DANDI_API_ROOT = "https://api.lincbrain.org/api/"
VITE_APP_SENTRY_DSN = "https://833c159dc622528b21b4ce4adef6dbf8@o4506237212033024.ingest.sentry.io/4506237213212672"
VITE_APP_SENTRY_ENVIRONMENT = "production"
VITE_CLOUDFRONT_NEUROGLANCER_URL = "https://neuroglancer.lincbrain.org/"
VITE_APP_WEBKNOSSOS_API_ROOT="https://webknossos-staging.lincbrain.org/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[[plugins]]
package = "/netlify/plugins/server-info-build"
